<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_1_PlcTask" Id="{21f3a158-4837-47ff-8ec7-29454a44967d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_1_PlcTask
VAR
//fbLogHandler: FB_LogHandler;
	// PRG_DCCM_MONO: INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_DCCM_MONO();
//fbLogHandler();
]]></ST>
    </Implementation>
    <LineIds Name="PRG_1_PlcTask">
      <LineId Id="19" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>